/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      2: "2px",
      3: "3px",
      4: "4px",
      5: "5px",
      6: "6px",
      8: "8px",
      12: "12px",
    },
    extend: {
      colors: {
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        "text-countdown": "var(--text-countdown)",
        "text-highlight": "var(--text-highlight)",
        "text-notice": "var(--text-notice)",
        "text-notice-icon": "var(--text-notice-icon)",
        "hover-color": "var(--hover-color)",
        "accent-color": "var(--accent-color)",
        "accent-reverse": "var(--accent-reverse)",
        "reverse-color": "var(--reverse-color)",
        "button-color": "var(--button-color)",
        "background-main": "var(--background-main)",
        "background-form": "var(--background-form)",
        "background-title": "var(--background-title)",
        "background-countdown": "var(--background-countdown)",
        "background-notice": "var(--background-notice)",
        "text-inactive": "var(--text-inactive)",
        "background-inactive": "var(--background-inactive)",
        "background-loading": "var(--background-loading)",
        "background-delayed": "var(--background-delayed)",
        "background-cancelled": "var(--background-cancelled)",
        "background-departed": "var(--background-departed)",
        "border-notice": "var(--border-notice)",
        "background-selected": "var(--background-selected)",
        "focus-color": "var(--focus-color)",
        "train-direct": "var(--train-direct)",
        "background-nochange": "var(--nochange)",
      },
    },
  },
  plugins: [],
};
